# Generated by Django 2.2.3 on 2019-07-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_tool', '0003_postcodelist_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcodelist',
            name='csv',
        ),
    ]
