# Generated by Django 2.2.3 on 2019-07-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_tool', '0004_remove_postcodelist_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcodelist',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
