# Generated by Django 2.2.3 on 2019-07-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_tool', '0006_postcodelist_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcodelist',
            name='csv',
            field=models.TextField(blank=True, default=''),
        ),
    ]
